version: "3.9"
services:
    node: 
        container_name: node-${PROJECT_NAME}
        build: .
        restart: always
        ports: 
            - "${NODE_PORT}:4000"
        volumes: 
            - ./api:/api   
        env_file:
            - .env 
        depends_on: 
            - mysql
    mysql: 
        image: mysql:8.0
        container_name: mysql-${PROJECT_NAME}
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            TZ: America/Guatemala
        volumes:
            - ${MYSQL_VOLUMES}:/var/lib/mysql 
        env_file:
            - .env