-- MySQL Script generated by MySQL Workbench
-- Sat Oct 29 09:39:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fintech
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fintech` ;

-- -----------------------------------------------------
-- Schema fintech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fintech` DEFAULT CHARACTER SET utf8 ;
USE `fintech` ;

-- -----------------------------------------------------
-- Table `fintech`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`person` ;

CREATE TABLE IF NOT EXISTS `fintech`.`person` (
  `id_person` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` BIGINT UNSIGNED NOT NULL,
  `full_name` VARCHAR(200) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `date_of_birth` DATE NULL,
  `state` BIT NULL DEFAULT 1,
  `creation_date` DATETIME NULL DEFAULT current_timestamp,
  `edition_date` DATETIME NULL,
  PRIMARY KEY (`id_person`),
  INDEX `fk_person_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_person_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `fintech`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fintech`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`user` ;

CREATE TABLE IF NOT EXISTS `fintech`.`user` (
  `id_user` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usermane` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NULL,
  `temporal_password` VARCHAR(45) NULL,
  `facebook` VARCHAR(100) NULL,
  `google` VARCHAR(100) NULL,
  `state` BIT NULL DEFAULT 1,
  `temporal_password_expiration` DATETIME NULL,
  `creation_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `edition_date` DATETIME NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
