-- MySQL Script generated by MySQL Workbench
-- Wed Nov  9 20:24:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fintech
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fintech` ;

-- -----------------------------------------------------
-- Schema fintech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fintech` DEFAULT CHARACTER SET utf8mb3 ;
USE `fintech` ;

-- -----------------------------------------------------
-- Table `fintech`.`campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`campaign` ;

CREATE TABLE IF NOT EXISTS `fintech`.`campaign` (
  `campaign_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `creacion_user_id` BIGINT UNSIGNED NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `campaign` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `state` CHAR(1) NULL DEFAULT '1',
  `creation_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `edition_date` TIMESTAMP NULL,
  PRIMARY KEY (`campaign_id`),
  INDEX `fk_campaign_user1_idx` (`creacion_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_campaign_user1`
    FOREIGN KEY (`creacion_user_id`)
    REFERENCES `fintech`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fintech`.`campaign_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`campaign_customer` ;

CREATE TABLE IF NOT EXISTS `fintech`.`campaign_customer` (
  `campaign_campaign_id` INT UNSIGNED NOT NULL,
  `customer_customer_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_table1_campaign1_idx` (`campaign_campaign_id` ASC) VISIBLE,
  INDEX `fk_table1_customer1_idx` (`customer_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_campaign1`
    FOREIGN KEY (`campaign_campaign_id`)
    REFERENCES `fintech`.`campaign` (`campaign_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `fintech`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fintech`.`campaign_form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`campaign_form` ;

CREATE TABLE IF NOT EXISTS `fintech`.`campaign_form` (
  `campaign_form_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campaign_id` INT UNSIGNED NOT NULL,
  `proccess_id` INT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `campaign_form` VARCHAR(45) NOT NULL,
  `settings` JSON NOT NULL,
  `state` CHAR(1) NULL,
  `creation_date` TIMESTAMP NULL DEFAULT current_timestamp,
  `edition_date` TIMESTAMP NULL,
  PRIMARY KEY (`campaign_form_id`),
  INDEX `fk_campaign_form_campaign1_idx` (`campaign_id` ASC) VISIBLE,
  INDEX `fk_campaign_form_proccess1_idx` (`proccess_id` ASC) VISIBLE,
  INDEX `fk_campaign_form_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_campaign_form_campaign1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `fintech`.`campaign` (`campaign_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaign_form_proccess1`
    FOREIGN KEY (`proccess_id`)
    REFERENCES `fintech`.`proccess` (`proccess_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaign_form_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fintech`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fintech`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`customer` ;

CREATE TABLE IF NOT EXISTS `fintech`.`customer` (
  `customer_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NULL,
  `campaign_form_id` BIGINT UNSIGNED NULL,
  `customer` VARCHAR(45) NOT NULL,
  `answers` JSON NULL,
  `state` CHAR(1) NULL DEFAULT '1',
  `creation_date` TIMESTAMP NULL DEFAULT current_timestamp,
  `edition_date` TIMESTAMP NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customer_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_customer_campaign_form1_idx` (`campaign_form_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fintech`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_campaign_form1`
    FOREIGN KEY (`campaign_form_id`)
    REFERENCES `fintech`.`campaign_form` (`campaign_form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fintech`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`person` ;

CREATE TABLE IF NOT EXISTS `fintech`.`person` (
  `person_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `full_name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `date_of_birth` DATE NULL,
  `state` CHAR(1) NULL DEFAULT '1',
  `creation_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `edition_date` DATETIME NULL,
  PRIMARY KEY (`person_id`),
  INDEX `fk_person_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `fintech`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `fintech`.`proccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`proccess` ;

CREATE TABLE IF NOT EXISTS `fintech`.`proccess` (
  `proccess_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `proccess` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `state` CHAR(1) NULL DEFAULT '1',
  PRIMARY KEY (`proccess_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fintech`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`request` ;

CREATE TABLE IF NOT EXISTS `fintech`.`request` (
  `request_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `campaign_id` INT UNSIGNED NOT NULL,
  `proccess_id` INT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NULL,
  `customer_id` BIGINT UNSIGNED NULL,
  `approved_user_id` BIGINT UNSIGNED NULL,
  `state` CHAR(1) NULL DEFAULT '1',
  `approval_date` TIMESTAMP NULL,
  `creation_date` TIMESTAMP NULL DEFAULT current_timestamp,
  `edition_date` TIMESTAMP NULL,
  PRIMARY KEY (`request_id`),
  INDEX `fk_request_campaign1_idx` (`campaign_id` ASC) VISIBLE,
  INDEX `fk_request_proccess1_idx` (`proccess_id` ASC) VISIBLE,
  INDEX `fk_request_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_request_customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_request_user2_idx` (`approved_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_request_campaign1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `fintech`.`campaign` (`campaign_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_proccess1`
    FOREIGN KEY (`proccess_id`)
    REFERENCES `fintech`.`proccess` (`proccess_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fintech`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `fintech`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_user2`
    FOREIGN KEY (`approved_user_id`)
    REFERENCES `fintech`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fintech`.`request_for_answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`request_for_answers` ;

CREATE TABLE IF NOT EXISTS `fintech`.`request_for_answers` (
  `request_id` BIGINT UNSIGNED NOT NULL,
  `campaign_form_id` BIGINT UNSIGNED NOT NULL,
  `answers` JSON NOT NULL,
  `state` CHAR NULL DEFAULT '1',
  `creation_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `edition_date` TIMESTAMP NULL,
  INDEX `fk_request_for_answers_request1_idx` (`request_id` ASC) VISIBLE,
  CONSTRAINT `fk_request_for_answers_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `fintech`.`request` (`request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_for_answers_campaign_form1`
    FOREIGN KEY (`campaign_form_id`)
    REFERENCES `fintech`.`campaign_form` (`campaign_form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fintech`.`type_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`type_user` ;

CREATE TABLE IF NOT EXISTS `fintech`.`type_user` (
  `type_user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_user` VARCHAR(45) NOT NULL,
  `state` CHAR(1) NULL DEFAULT '1',
  PRIMARY KEY (`type_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fintech`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fintech`.`user` ;

CREATE TABLE IF NOT EXISTS `fintech`.`user` (
  `user_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_user_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NULL,
  `temporal_password` VARCHAR(45) NULL,
  `provider` VARCHAR(100) NULL,
  `provider_id` VARCHAR(100) NULL,
  `state` CHAR NULL DEFAULT 1,
  `temporal_password_expiration` VARCHAR(100) NULL,
  `creation_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `edition_date` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_type_user1_idx` (`type_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_type_user1`
    FOREIGN KEY (`type_user_id`)
    REFERENCES `fintech`.`type_user` (`type_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
